apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: admin
  template:
    metadata:
      labels:
        component: admin
    spec:
      containers:
        - name: client
          image: sainthkh/store-admin
          ports:
            - containerPort: 8000
